groups:
  - name: application_alerts
    rules:
      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le, endpoint)) > 0.4
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High request latency detected on {{ $labels.endpoint }}"
          description: "The 95th percentile latency for endpoint {{ $labels.endpoint }} is {{ $value }}s, which is above the threshold of 0.4s."
      - alert: AppDown
        expr: up{job="python-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Python application instance down"
          description: "The python-app job instance {{ $labels.instance }} is down."